services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      # This should be the connection string for your Supabase database
      - DATABASE_URL=postgresql://user:password@db.supabase.co:5432/postgres

  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "8080:80"
